name: Build and Release DoomHUD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a release'
        required: true
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Cache Swift packages
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-
          
    - name: Build app
      run: |
        # Make build script executable
        chmod +x build_app_signed.sh
        
        # Build with ad-hoc signing (no certificate configured)
        echo "Using ad-hoc signing"
        ./build_app_signed.sh
        
    - name: Create ZIP archive
      run: |
        # Create a ZIP file of the app
        zip -r DoomHUD-${{ github.ref_name }}.zip DoomHUD.app
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: DoomHUD-${{ github.ref_name }}
        path: |
          DoomHUD.app
          DoomHUD-${{ github.ref_name }}.zip
          
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.create_release == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: DoomHUD-${{ github.ref_name }}.zip
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## DoomHUD Release ${{ github.ref_name }}
          
          ### Installation
          1. Download `DoomHUD-${{ github.ref_name }}.zip`
          2. Unzip and move `DoomHUD.app` to your Applications folder
          3. Run the app and grant necessary permissions:
             - Accessibility
             - Input Monitoring  
             - Camera
             - Screen Recording
          
          ### What's Changed
          See the commit history for detailed changes.
          
          **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
